apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    app: cocreate-api
  name: cocreate-api
  namespace: default
spec:
  selector:
    matchLabels:
      app: cocreate-api
  template:
    metadata:
      labels:
        app: cocreate-api
    spec:
      containers:
        - image: cocreate-api
          imagePullPolicy: Always
          name: cocreate-api
          env:
            - name: PORT
              value: '3002'
          ports:
            - containerPort: 3002
              name: api
              protocol: TCP
      imagePullSecrets:
        - name: github
      restartPolicy: Always
      nodeSelector:
        nodeType: application
